const ON_SWITCH_ACCOUNT_START = 'ON_SWITCH_ACCOUNT_START'
const ON_SWITCH_ACCOUNT_END = 'ON_SWITCH_ACCOUNT_END'
const ON_IMPORT_ACCOUNT = 'ON_IMPORT_ACCOUNT'

const RESET_DELETE_STATUS = 'RESET_DELETE_STATUS'
const UPDATE_BACKUP_STATUS = 'UPDATE_BACKUP_STATUS'
const ON_DELETE_ACCOUNT_START = 'ON_DELETE_ACCOUNT_START'
const ON_DELETE_ACCOUNT_SUC = 'ON_DELETE_ACCOUNT_SUC'
const ON_DELETE_ACCOUNT_FAIL = 'ON_DELETE_ACCOUNT_FAIL'


const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START'
const CREATE_ACCOUNT_SUC = 'CREATE_ACCOUNT_SUC'
const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL'


const IMPORT_ACCOUNT_START = 'IMPORT_ACCOUNT_START'
const IMPORT_ACCOUNT_SUC = 'IMPORT_ACCOUNT_SUC'
const IMPORT_ACCOUNT_FAIL = 'IMPORT_ACCOUNT_FAIL'

const DELETE_MNEMONIC = 'DELETE_MNEMONIC'
const DELETE_MNEMONIC_START = 'DELETE_MNEMONIC_START'

const GLOBAL_ALL_ACCOUNTS_INFO = 'GLOBAL_ALL_ACCOUNTS_INFO'
const GLOBAL_CURRENT_ACCOUNT_INFO = 'GLOBAL_CURRENT_ACCOUNT_INFO'

const UPDATE_BACKUP_STATUS_SUCC = 'UPDATE_BACKUP_STATUS_SUCC'

const CHANGE_BACKUP_MODAL_TIMES = 'CHANGE_BACKUP_MODAL_TIMES'

export {
	ON_SWITCH_ACCOUNT_START,
	ON_SWITCH_ACCOUNT_END,
	ON_IMPORT_ACCOUNT,

	RESET_DELETE_STATUS,
	UPDATE_BACKUP_STATUS,	


	ON_DELETE_ACCOUNT_START,
	ON_DELETE_ACCOUNT_SUC,
	ON_DELETE_ACCOUNT_FAIL,

	CREATE_ACCOUNT_START,
	CREATE_ACCOUNT_SUC,
	CREATE_ACCOUNT_FAIL,

	IMPORT_ACCOUNT_START,
	IMPORT_ACCOUNT_SUC,
	IMPORT_ACCOUNT_FAIL,

	DELETE_MNEMONIC,
	DELETE_MNEMONIC_START,

	GLOBAL_ALL_ACCOUNTS_INFO,

	GLOBAL_CURRENT_ACCOUNT_INFO,

	UPDATE_BACKUP_STATUS_SUCC,

	CHANGE_BACKUP_MODAL_TIMES
}