const SEND_VERIF_CODE_START = 'SEND_VERIF_CODE_START'
const SEND_VERIF_CODE_SUC = 'SEND_VERIF_CODE_SUC'
const SEND_VERIF_CODE_FAIL = 'SEND_VERIF_CODE_FAIL'

const BIND_ADDRESS_START = 'BIND_ADDRESS_START'
const BIND_ADDRESS_SUC = 'BIND_ADDRESS_SUC'
const BIND_ADDRESS_FAIL = 'BIND_ADDRESS_FAIL'

const RESET_ACTIVITY_STATUS = 'RESET_ACTIVITY_STATUS'
export {
	SEND_VERIF_CODE_START,
	SEND_VERIF_CODE_SUC,
	SEND_VERIF_CODE_FAIL,

	BIND_ADDRESS_START,
	BIND_ADDRESS_SUC,
	BIND_ADDRESS_FAIL,

	RESET_ACTIVITY_STATUS
}