const MAKE_TX_BY_ETZ_START = 'MAKE_TX_BY_ETZ_START'
const MAKE_TX_BY_ETZ_SUC = 'MAKE_TX_BY_ETZ_SUC'
const MAKE_TX_BY_ETZ_FAIL = 'MAKE_TX_BY_ETZ_FAIL'
const MAKE_TX_BY_ETZ_HASH = 'MAKE_TX_BY_ETZ_HASH'
const RESET_TX_STATUS = 'RESET_TX_STATUS'

export {
	MAKE_TX_BY_ETZ_START,
	MAKE_TX_BY_ETZ_SUC,
	MAKE_TX_BY_ETZ_FAIL,
	MAKE_TX_BY_ETZ_HASH,
	RESET_TX_STATUS
}